"""add payments

Revision ID: 1a826956efa3
Revises: 3610d9bc802b
Create Date: 2026-09-04 04:01:55.403424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a826956efa3'
down_revision: Union[str, Sequence[str], None] = '3610d9bc802b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('from_member_id', sa.UUID(), nullable=False),
    sa.Column('to_member_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_payments_amount_cents_positive'),
    sa.CheckConstraint('from_member_id != to_member_id', name='ck_payments_from_ne_to'),
    sa.ForeignKeyConstraint(['from_member_id'], ['trip_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_member_id'], ['trip_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_from_member_id'), 'payments', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_payments_to_member_id'), 'payments', ['to_member_id'], unique=False)
    op.create_index(op.f('ix_payments_trip_id'), 'payments', ['trip_id'], unique=False)
    # NOTE: autogenerate also proposed dropping the `expense_category`,
    # `expense_type`, and `member_role` check constraints here. That's a
    # false positive from how SQLAlchemy's non-native Enum constraints
    # get reflected back — the constraints are unchanged, so those drops
    # (and their downgrade counterparts) were intentionally removed from
    # this migration, matching 970c0b41fe7b.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_trip_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_to_member_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_from_member_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
