"""add payment status and responded_at

Revision ID: 21eaa0bde77d
Revises: 9eaf99310ca2
Create Date: 2026-09-16 18:00:19.886069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eaa0bde77d'
down_revision: Union[str, Sequence[str], None] = '9eaf99310ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: existing rows need a value for this
    # new NOT NULL column, and every pre-existing payment was recorded
    # under the old immediate-effect behavior, i.e. already confirmed.
    op.add_column(
        'payments',
        sa.Column(
            'status',
            sa.Enum('pending', 'confirmed', 'rejected', name='payment_status', native_enum=False, create_constraint=True),
            server_default='confirmed',
            nullable=False,
        ),
    )
    op.add_column('payments', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate also proposed dropping the `expense_category`,
    # `expense_type`, and `member_role` check constraints here — same
    # false positive documented in migration 970c0b41fe7b. Left out.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'responded_at')
    op.drop_column('payments', 'status')
    # ### end Alembic commands ###
