"""add invited email to trip members

Revision ID: 3610d9bc802b
Revises: 07fd5d981976
Create Date: 2026-09-03 23:47:35.969658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3610d9bc802b'
down_revision: Union[str, Sequence[str], None] = '07fd5d981976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_members', sa.Column('invited_email', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_trip_members_invited_email'), 'trip_members', ['invited_email'], unique=False)
    # NOTE: autogenerate also proposed dropping the `expense_category`,
    # `expense_type`, and `member_role` check constraints here — same
    # false positive documented in migration 970c0b41fe7b. Left out.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_members_invited_email'), table_name='trip_members')
    op.drop_column('trip_members', 'invited_email')
    # ### end Alembic commands ###
