"""add trip settlement reminder tracking

Revision ID: 9eaf99310ca2
Revises: 1a826956efa3
Create Date: 2026-09-04 04:46:30.351859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eaf99310ca2'
down_revision: Union[str, Sequence[str], None] = '1a826956efa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping the `expense_category`,
    # `expense_type`, and `member_role` check constraints here. That's a
    # false positive from how SQLAlchemy's non-native Enum constraints
    # get reflected back — the constraints are unchanged, so those drops
    # (and their downgrade counterparts) were intentionally removed from
    # this migration, matching 970c0b41fe7b.
    op.add_column('trips', sa.Column('end_date_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('last_weekly_reminder_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'last_weekly_reminder_date')
    op.drop_column('trips', 'end_date_reminder_sent_at')
    # ### end Alembic commands ###
